name: build
on:
  push:
  pull_request:

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install tox
      - run: python -m tox -e mypy-test

  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {name: '3.7', python: '3.7', tox: py37}
          - {name: '3.11', python: '3.11', tox: py311}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - run: python -m pip install tox
      - run: python -m tox -e ${{ matrix.tox }}

  # this duplicates pre-commit.ci, so only run it on tags
  # it guarantees that linting is passing prior to a release
  lint-pre-release:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install tox
      - run: python -m tox -e lint

  release:
    needs: [mypy, tests, lint-pre-release]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: install requirements
        run: python -m pip install build twine
      - name: build dists
        run: python -m build
      - name: check package metadata
        run: twine check dist/*
      - name: publish
        run: twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
